pipeline {
    agent { label 'dockerserver' }

    stages {
        stage('Creating private environment'){
            steps{
                sh 'python3 -m venv env'
                sh 'source env/bin/activate'
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'pip3 install -r src/Data_RBUK/requirements.txt '
            }
        }
        stage('Execute script') {
            steps {
                sh 'python3 src/Data_RBUK/send_data_to_RBUK.py '
            }
        }
    }
}
