pipeline {
    agent { docker { image 'python:3.10.7-alpine' } }

    stages {
        stage('Hello') {
            steps {
                sh 'python --version'
            }
        }
    }
}
